### ISSUE TITLE
Publish `adarshpandeyin.search-github-users-extension` to Open VSX

### ISSUE THREAD

**Issue by goyalyashpal** [aadarshp31/github-search-web-extension#1]
Hi!
Congratulations of getting ur extension [published]. I just thought to ask that do u have any plans to publish ur extension on open-vsx??
See this for more details: [adarshpandeyin.search-github-users-extension]
Thanks!

[published]: https://code.visualstudio.com/updates/v1_62#_web-extensions
[adarshpandeyin.search-github-users-extension]: https://open-vsx.org/vscode/item?itemName=adarshpandeyin.search-github-users-extension

**Comment by aadarshp31** [comment]
Thanks @yashpalgoyal1304 for your kind words.

Yes, I'm currently in the process. The Open-VSX platform is not providing publishing accounts easily nowadays due to some security and legal reasons. I'll be publishing there as soon as I get the publishing rights. 
Will update the status here soon.
Read more about it [here](https://github.com/eclipse/openvsx/wiki/Namespace-Access)

You're requiring that for OpenVSCode-server or code-server right? 
Or are there other reasons for publishing in the Open-VSX Repository?

**Comment by goyalyashpal** [comment]
> You're requiring that for OpenVSCode-server or code-server right?
> Or are there other reasons for publishing in the Open-VSX Repository?

nope, i asked that for [VSCodium](https://vscodium.com). But open-vsx is also used by [Theia](https://theia-ide.org) based products and [gitpod](https://www.gitpod.io) etc

**Comment by aadarshp31** [comment]
Yeah, I've worked with VSCodium as well. Most of them use the Open-VSX repository as a marketplace. <br />
Anyways, I've published the extension in the Open-VSX repo just now. You can find it at the [link](https://open-vsx.org/extension/adarshpandeyin/search-github-users-extension) but the namespace ownership is under process here [Github Issue](https://github.com/EclipseFdn/open-vsx.org/issues/743) so you might see some warning messages at the extension's page.

You should be able to use the extension rightaway. Give it a go and let me know if you need anything.<br />

<b>Sidenote:</b> Gitpod has ditched [Theia](https://github.com/eclipse-theia/theia) in 2021 for [VS Code](https://github.com/microsoft/vscode/) as their source.
